### PR TITLE
Change default linejoin and linecap to preserve previous behavior

### LINKED ISSUE #61: Default drawing behaviour different after merging agg2.4
As I brought up in #50, the default line-end and line-cap arguments are different after merging the agg 2.4 update, unexpectedly changing the way various aggdraw-generated shapes look. Here are two screenshots from the same aggdraw-rendered experiment program, the first pre-2.4 and the second post-2.4:

Screen Shot 2019-08-13 at 7 21 10 PM

Screen Shot 2019-08-13 at 7 19 48 PM

If you download both the images and switch back and forth between them with Quick Look or something (ignoring the missing left line, that's just trial-to-trial variation), you can see that:

1. The corners of the boxes are now rounded, whereas before they were completely square.
2. The line in the middle of the box (created with the line() method of the aggdraw.Draw(), not the .rectangle() method) is slightly longer for some reason.
3. The asterisk in the middle is slightly thicker.

I'm able to revert the drawing behaviour for both 1 and 2 to the pre-2.4 defaults by adding `linejoin = 0` and `linecap = 0` to the arguments when creating the Pen object, but this breaks backwards compatibility with old aggdraw versions, which lack these arguments. My personal preference would be to revert the defaults here to the old defaults before the next release, since a lot of the use of aggdraw in my field (cognitive science research) is in older Python experiments for generating stimuli, and people trying to revive/replicate one of those experiments (largely one-off scripts with no real maintainer) are highly unlikely to realize the shapes look different than they did 5-10 years ago and add the new arguments accordingly.

The thicker asterisk remains unchanged with the above overrides, however, which appears to be a regression because the thickness/size of the asterisk is exactly as specified pre-2.4 but appears to be an extra 1 pixel thicker/larger post-2.4. I'll see if I can figure out a minimal example that showcases this bug clearly, since what I have here is all wrapped in my own drawing/rendering code.

EDIT: To revert to the old defaults in aggdraw itself, I believe all that's required is replacing the `agg::round_join` with `agg::miter_join` and `agg::round_cap` with `agg::butt_cap` in this section here:

https://github.com/pytroll/aggdraw/blob/e9d7bcb49faf688e29b3013bde6621bde82f110a/aggdraw.cxx#L1823-L1833

### PR DESCRIPTION
**Pull request by djhoese**
Closes #61. This changes the default line join and cap types to miter and butt which preserves the previous Agg settings. @dov any idea/reason why these defaults were changed when switching to agg 2.4? Also, @a-hurst please review.

I got the mapping of the constants [here](https://github.com/tomhughes/agg/blob/0123842bf579f0a79c444b28abe2ecdd5463acfa/include/agg_math_stroke.h#L29-L44) since the main antigrain website seems broken. Using raw enum integers this way is not the most flexible or backwards compatible. However, mapping strings to the constants is not the most straight forward thing to do in C++ so I will wait until we migrate to cython to change this to accept ints (backwards compatible) or strings for the names of the join and cap types. I did realize that #3 was doing this string checking (FYI @ simonkolotov), but since it looks like the API in 2.4 changed quite a bit, I didn't really have time to adjust that PR to work for this. This at least preserves the current behavior.

### CODE REVIEW

**Comment by djhoese** [comment]
FYI the failing appveyor is a problem with `ci-helpers`. This won't be an issue in a couple days when my fixes to `ci-helpers` are merged.

**Comment by a-hurst** [comment]
It looks like the line_cap line still needs to be changed to revert to the previous behaviour. Otherwise, this looks good! The new docstrings are great.

**Comment by djhoese** [comment]
Sorry, I completely forgot about this. Should be complete. Will wait for tests.

**Comment by djhoese** [comment]
@a-hurst Any chance you a powershell expert? The appveyor builds are failing because (I think) the `if` statements are running commands like `conda activate test` in a separate scope that isn't affecting the rest of the script activation. This is different than how conda used to be activated which I think was `call activate test`.

**Comment by a-hurst** [comment]
@djhoese unfortunately not, I'm very much a UNIX person so I really had to fumble my way through setting up appveyor to get aggdraw builds working originally. That said, maybe it's worth a shot putting the "%CMD_IN_ENV%" in front of the "conda activate test" line, or alternatively putting the "call" in front of "conda activate test"? The only way I managed to get it working in the first place was a lot of trial and error.

File: ci/travis-install.sh [hunk 1]
```diff
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 if [[ "${BUILDMODE}" == "ASTROPY" ]]; then
-    git clone --depth 1 git://github.com/astropy/ci-helpers.git
+#    git clone --depth 1 git://github.com/astropy/ci-helpers.git
+    git clone --depth 1 -b all-the-fixes git://github.com/djhoese/ci-helpers.git
```
Comment (mraspaud) [inline ci/travis-install.sh]: Can this be reverted now ?

Comment (djhoese) [reply ci/travis-install.sh]: Yes. I'm guessing I'll still have issues though with the Windows conda activation.

Comment (djhoese) [reply ci/travis-install.sh]: This is done but Windows still hates me.

**Comment by djhoese** [comment]
@a-hurst Now that this is merged we should see how different our various use cases are. I will try running some of the pytroll package tests (pycoast) with the master branch of aggdraw and see if/how many of our tests fail.
